#### 1. Generate a 1D NumPy array containing numbers from -2 to 2 in increments of 0.2. Use optional start and step arguments of np.arange() function.

In [9]:
import numpy as np

np.arange(-2, 2, 0.2)

array([-2.0000000e+00, -1.8000000e+00, -1.6000000e+00, -1.4000000e+00,
       -1.2000000e+00, -1.0000000e+00, -8.0000000e-01, -6.0000000e-01,
       -4.0000000e-01, -2.0000000e-01, -4.4408921e-16,  2.0000000e-01,
        4.0000000e-01,  6.0000000e-01,  8.0000000e-01,  1.0000000e+00,
        1.2000000e+00,  1.4000000e+00,  1.6000000e+00,  1.8000000e+00])

#### 2. Generate another 1D NumPy array containing 11 equally spaced values between 0.5 and 1.5. Extract every second element of the array

In [11]:
array = np.linspace(0.5, 1.5, 11)
array[1]

0.6

#### 3. Create a 4x4 array with arbitrary values.Extract every element from the second row.

In [39]:
a = np.arange(16, dtype=float)
r = a.reshape(4,4)
r[1,:]

array([4., 5., 6., 7.])

#### 4. Extract every element from the third column

In [40]:
r[:,2]

array([ 2.,  6., 10., 14.])

#### 5. Assign a value of 0.21 to upper left 2x2 subarray.

In [41]:
r[0:2,0:2] = 0.21
r

array([[ 0.21,  0.21,  2.  ,  3.  ],
       [ 0.21,  0.21,  6.  ,  7.  ],
       [ 8.  ,  9.  , 10.  , 11.  ],
       [12.  , 13.  , 14.  , 15.  ]])

#### 6. Read an 2D array from the file exercise1_4.dat. You can usethe function np.loadtxt():

data = np.loadtxt(‘exercise1_4.dat’)

#### Split the array into four subblocks (upper left, upper right, lower left, lower right) using np.split(). Construct then the full array again with np.concatenate(). You can visualize the various arrays with matplotlib’s imshow(), i.e. import pylab pylab.imshow(data)
